name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    strategy:
      matrix:
        context: ["rlang"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            context:
              - "${{ matrix.context }}/**"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: steps.filter.outputs.context == 'true'
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.context }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
